import Head from 'next/head'
import styles from '../styles/Home.module.css'
import fs from 'fs'
import matter from 'gray-matter';
import Link from 'next/link';
import {Footer} from '../components/Footer';

export async function getStaticProps() {
  const files = fs.readdirSync('posts');
  const posts = files.map((filename) => {
    const slug = filename.replace('.md', '');
    const readFiles = fs.readFileSync(`posts/${filename}`)
    const { data: frontMatter } = matter(readFiles);

    return {
      slug, frontMatter
    }
  })
  return {
    props: {
      posts
    }
  }
}

export default function Home({ posts }) {
  return (
    <div className={ styles.container}>
      <Head>
        <title>MnxBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full font-sans leading-normal tracking-normal my-0 mx-auto'>
        <div className='text-center select-none'>
          <p className='text-4xl lg:text-5xl mt-5 mb-2 font-bold cursor-pointer text-teal-800'>mnxBlog;</p>
          <p className='text-gray-600 text-lg mb-4 font-semibold'>Open source is a thankless job. We do it anyway.👋</p>
        </div>
        <hr className='border' />
        <div>
          { posts?.map((post) => {
            return (
              <Link key={ `${post.slug}` } href={ `/blog/${post.slug}` }>
                <div className={styles.borderGradient +" p-5 hover:bg-slate-100 cursor-pointer select-none"}>
                  <div key={ post.frontMatter.id } className='mb-4'>
                    <span className='text-sm font-semibold text-slate-700'>{post.frontMatter.date}</span>
                    <h1 className='text-2xl font-bold text-slate-700'>{ post.frontMatter.title }</h1>
                    <p className='mt-3 text-lg opacity-50 font-semibold'>{ post.frontMatter.desc }</p>
                  </div>
                </div>
              </Link>
            )
          }) }
        </div>
      </main>
      {/* absolute */}
      <Footer />
    </div>
  )
}
